name: baserow
description: A Dart client library for managing Baserow databases and tables.
version: 0.0.2
repository: https://github.com/cedricziel/baserow-dart

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.0
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ">=4.0.0 <6.0.0"
  test: ^1.24.0
