name: baserow
description: A Dart client library for managing Baserow databases and tables.
version: 2.0.0
repository: https://github.com/cedricziel/baserow-dart
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  http:
  json_annotation:
  jwt_decoder:
  web_socket_channel:

dev_dependencies:
  async:
  build_runner:
  fake_async:
  json_serializable:
  lints:
  mockito:
  stream_channel:
  test:
