name: baserow
description: A Dart client library for managing Baserow databases and tables.
version: 2.0.0
repository: https://github.com/cedricziel/baserow-dart
resolution: workspace

environment:
  sdk: ^3.6.0
